### ISSUE TITLE
Dockerfile build can't run example missions

### ISSUE THREAD

**Issue by frogmasta** [clydemcqueen/orca4#7]
@clydemcqueen
I've recently decided to use this library to communicate with the BlueROV through ROS2. I built the docker file included in the repository and tried to execute the example mission provided in the documentation. It worked fine at first until all of a sudden there was a TCP error. I've copied the relevant error messages below. 

[controller_server-14] [INFO] [1675701766.523667448] [controller_server]: Passing new path to controller.
[ardusub-2] ERROR: Floating point exception - aborting
[ardusub-2] Running: sh dumpstack.sh 85909 >dumpstack.sh_ardusub.85909.out 2>&1
[ardusub-2] Failed
[ardusub-2] Running: sh dumpcore.sh 85909 >dumpcore.sh_ardusub.85909.out 2>&1
[ardusub-2] Failed
[mavros_node-8] Error:   mavconn: tcp0: receive: Connection reset by peer
[mavros_node-8]          at line 283 in ./src/tcp.cpp
[mavros_node-8] Error:   mavconn: tcp0: shutdown: Transport endpoint is not connected
[mavros_node-8]          at line 194 in ./src/tcp.cpp
[ERROR] [ardusub-2]: process has died [pid 85909, exit code -6, cmd 'ardusub -S -w -M JSON --defaults /home/orca4/colcon_ws/install/orca_bringup/share/orca_bringup/cfg/sub.parm -I0 --home 33.810313,-118.39386700000001,0.0,270.0'].
[mavros_node-8] Error:   mavconn: tcp0: send: channel closed!
[mavros_node-8]          at line 234 in ./src/tcp.cpp

What's the cause of this error? Thanks.

**Comment by frogmasta** [comment]
Hi Clyde!

Thanks for looking into it a bit. Unfortunately, it didn't seem to fix the issue as I received the same Floating Point Exception.

I'm copying below another error message I just got. I realized that every time it crashed it was right after attempting to initialize the odometry.  

mavros_node-8] [INFO] [1675795855.387838482] [mavros.sys]: FCU: EKF3 IMU0 yaw aligned
[manager-9] [INFO] [1675795858.836524125] [manager]: setting message rates to 20 hz every 10s
[mavros_node-8] [INFO] [1675795858.955341551] [mavros.imu]: IMU: Attitude quaternion IMU detected!
[base_controller-10] [INFO] [1675795859.058081915] [base_controller]: EKF is running, state => RUN_NO_MAP
[manager-9] [INFO] [1675795859.058799056] [manager]: EKF is running
[base_controller-10] [INFO] [1675795859.082343166] [base_controller]: initialize odometry to {{-0.000138908, -0.000141547, -0.183731}, {0, 0, -5.75734e-05}}
[ardusub-2] ERROR: Floating point exception - aborting
[ardusub-2] Running: sh dumpstack.sh 285661 >dumpstack.sh_ardusub.285661.out 2>&1
[ardusub-2] Failed
[ardusub-2] Running: sh dumpcore.sh 285661 >dumpcore.sh_ardusub.285661.out 2>&1
[ardusub-2] Failed
[mavros_node-8] Error:   mavconn: tcp0: receive: Connection reset by peer
[mavros_node-8]          at line 283 in ./src/tcp.cpp
[mavros_node-8] Error:   mavconn: tcp0: shutdown: Transport endpoint is not connected
[mavros_node-8]          at line 194 in ./src/tcp.cpp

Hope you can take a look next week!

**Comment by Codaero** [comment]
Yes I am also getting a floating point exception 10-20 seconds after running sim_launch.py

**Comment by clydemcqueen** [comment]
I was able to fix this by copying the SDF changes, see the linked PR.

It would be nice to catch the overflow in ArduSub & not crash, but I'll leave that for another day.

**Comment by frogmasta** [comment]
Thanks Clyde, the fix worked! I'll mark this issue as closed.
